{"name": "验证异常处理", "status": "passed", "description": "确保异常被正确捕获", "steps": [{"name": "触发除以零异常", "status": "broken", "statusDetails": {"message": "ZeroDivisionError: division by zero\n", "trace": "  File \"C:\\Users\\xlc\\PycharmProjects\\Cryptography_experiments\\test\\experiments1\\test_Hill.py\", line 22, in test_exception_handling\n    1 / 0\n    ~~^~~\n"}, "start": 1741868060344, "stop": 1741868060344}], "start": 1741868060344, "stop": 1741868060344, "uuid": "e56cde71-707a-4beb-8623-a57fb536ae04", "historyId": "bd45a4dc69b0edfa2792cc2d8be1b3b3", "testCaseId": "bd45a4dc69b0edfa2792cc2d8be1b3b3", "fullName": "test_Hill.TestDemo#test_exception_handling", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "strict"}, {"name": "suite", "value": "test_Hill"}, {"name": "subSuite", "value": "TestDemo"}, {"name": "host", "value": "DESKTOP-J7LE7IQ"}, {"name": "thread", "value": "28540-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_Hill"}]}